### ISSUE TITLE
Enter key in commands

### ISSUE THREAD

**Issue by ostrosablin** [gurrhack/ForkFront-Android#2]
I think it would be convenient to be able to define commands with Enter key. Consider this:

E-Elbereth[Enter] - Engrave dust Elbereth in one click
DX[Enter].[Enter] - Drop all BUC-unknown items on altar

and so on.

However, there's some quirks. First, it's /possible/ to define such commands in run-time by entering a line-break (because add-command input is multiline). However, because this option is whitespace-separated, when NetHack is restarted, such commands break (and panel is reloaded incorrectly afterwards).

Second, newlines in commands make their buttons look weird (they're lower on panel). This could be solved by custom single-line label.

Third, above example don't quite work. E.g. command

>DX
> 

Would work (Select X in drop dialog and go next). However, this:

>DX
>.
> 

Won't work, not sure why. Dot should be equal to "select all". However something like this:

>DX
>()[]*%!/?
> 

To select all item classes and drop them would work. I guess it's some ForkFront implementation issue.

Being able to input Enter from panel commands could greatly help in automating tedious tasks, such as listed above and even more.

**Comment by gurrhack** [comment]
You can actually input "Enter" with the string "\n". So your first example works if you use the command "E-Elbereth\n". You can also do Escape with the string "\e" but I'm not sure if that's ever useful.

The dot should select all. It's just a bug. I'll fix that.

**Comment by ostrosablin** [comment]
Oh, I see. Didn't think of that (but tried ^j and ^m, which emit newline/carriage return in tty).

Then it's probably makes sense to disallow multiline input for commands (because it will break on app restart anyway). Or it could be left as-is, but after input, actual newlines should be replaced with escape sequences.

**Comment by ostrosablin** [comment]
Actually, I've found case where backspace escape sequence (\b?) would be useful.

When something is already engraved, there's a question, whether to wipe existing engraving or not. But Dust-E command would be universal if there's support for backspace escape char:

"E-n\bElbereth\n:"

So, the command would work both if there's an existing engraving, and if there's no engraving, the extra "n" before text could be erased by backspace.

**Comment by gurrhack** [comment]
Also added select/clear all with dot/minus
adc9cc90891717c7a1aa1cd2ca8ee7dfcd8d43f5
